// REGISTER NEW USER
POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "fred",
    "password": "123"
}

###
// LOGIN 
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "fred",
    "password": "123"
}

###

// LOGOUT
POST http://localhost:3000/api/auth/logout HTTP/1.1
content-type: application/json

{
    "username": "fred",
    "password": "123"
}

###